// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	account "github.com/fajaramaulana/shared-proto-payment/proto/account"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// AccountServiceClient is an autogenerated mock type for the AccountServiceClient type
type AccountServiceClient struct {
	mock.Mock
}

// GetAccount provides a mock function with given fields: ctx, in, opts
func (_m *AccountServiceClient) GetAccount(ctx context.Context, in *account.AccountRequest, opts ...grpc.CallOption) (*account.AccountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *account.AccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *account.AccountRequest, ...grpc.CallOption) (*account.AccountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *account.AccountRequest, ...grpc.CallOption) *account.AccountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.AccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *account.AccountRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountByUser provides a mock function with given fields: ctx, in, opts
func (_m *AccountServiceClient) GetAccountByUser(ctx context.Context, in *account.AccountRequestByUser, opts ...grpc.CallOption) (*account.AccountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByUser")
	}

	var r0 *account.AccountResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *account.AccountRequestByUser, ...grpc.CallOption) (*account.AccountResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *account.AccountRequestByUser, ...grpc.CallOption) *account.AccountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.AccountResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *account.AccountRequestByUser, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAccountServiceClient creates a new instance of AccountServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountServiceClient {
	mock := &AccountServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
