// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	notification "github.com/fajaramaulana/shared-proto-payment/proto/notification"
	mock "github.com/stretchr/testify/mock"
)

// NotificationServiceServer is an autogenerated mock type for the NotificationServiceServer type
type NotificationServiceServer struct {
	mock.Mock
}

// SendNotification provides a mock function with given fields: _a0, _a1
func (_m *NotificationServiceServer) SendNotification(_a0 context.Context, _a1 *notification.NotificationRequest) (*notification.NotificationResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SendNotification")
	}

	var r0 *notification.NotificationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *notification.NotificationRequest) (*notification.NotificationResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *notification.NotificationRequest) *notification.NotificationResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notification.NotificationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *notification.NotificationRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedNotificationServiceServer provides a mock function with given fields:
func (_m *NotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {
	_m.Called()
}

// NewNotificationServiceServer creates a new instance of NotificationServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationServiceServer {
	mock := &NotificationServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
