// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	payment "github.com/fajaramaulana/shared-proto-payment/proto/payment"
)

// PaymentServiceClient is an autogenerated mock type for the PaymentServiceClient type
type PaymentServiceClient struct {
	mock.Mock
}

// CreatePayment provides a mock function with given fields: ctx, in, opts
func (_m *PaymentServiceClient) CreatePayment(ctx context.Context, in *payment.PaymentRequest, opts ...grpc.CallOption) (*payment.PaymentResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 *payment.PaymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *payment.PaymentRequest, ...grpc.CallOption) (*payment.PaymentResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *payment.PaymentRequest, ...grpc.CallOption) *payment.PaymentResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.PaymentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *payment.PaymentRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentStatus provides a mock function with given fields: ctx, in, opts
func (_m *PaymentServiceClient) GetPaymentStatus(ctx context.Context, in *payment.PaymentStatusRequest, opts ...grpc.CallOption) (*payment.PaymentStatusResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentStatus")
	}

	var r0 *payment.PaymentStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *payment.PaymentStatusRequest, ...grpc.CallOption) (*payment.PaymentStatusResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *payment.PaymentStatusRequest, ...grpc.CallOption) *payment.PaymentStatusResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment.PaymentStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *payment.PaymentStatusRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentServiceClient creates a new instance of PaymentServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentServiceClient {
	mock := &PaymentServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
