// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeNotificationServiceServer is an autogenerated mock type for the UnsafeNotificationServiceServer type
type UnsafeNotificationServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedNotificationServiceServer provides a mock function with given fields:
func (_m *UnsafeNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {
	_m.Called()
}

// NewUnsafeNotificationServiceServer creates a new instance of UnsafeNotificationServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeNotificationServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeNotificationServiceServer {
	mock := &UnsafeNotificationServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
