// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	user "github.com/fajaramaulana/shared-proto-payment/proto/user"
	mock "github.com/stretchr/testify/mock"
)

// UserServiceServer is an autogenerated mock type for the UserServiceServer type
type UserServiceServer struct {
	mock.Mock
}

// GetUser provides a mock function with given fields: _a0, _a1
func (_m *UserServiceServer) GetUser(_a0 context.Context, _a1 *user.UserRequest) (*user.UserResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *user.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.UserRequest) (*user.UserResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *user.UserRequest) *user.UserResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *user.UserRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedUserServiceServer provides a mock function with given fields:
func (_m *UserServiceServer) mustEmbedUnimplementedUserServiceServer() {
	_m.Called()
}

// NewUserServiceServer creates a new instance of UserServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserServiceServer {
	mock := &UserServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
