name: Versioning and Generate Protobuf

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  versioning:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install Protobuf and Go Plugins
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

      - name: Run Makefile to Generate Protobuf
        run: |
          make all

      - name: Auto Versioning (Tagging)
        run: |
          # Try to get the latest tag, default to 0.0.0 if none exists
          CURRENT_VERSION=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$NF++;print}')
          git tag $NEW_VERSION
          git push origin $NEW_VERSION
        shell: bash
