name: Versioning and Generate Protobuf

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  versioning:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install Protobuf and Go Plugins
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

      - name: Run Makefile to Generate Protobuf
        run: |
          make all

      - name: Auto Versioning (Tagging)
        run: |
          CURRENT_VERSION=$(git describe --tags --abbrev=0)
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$NF++;print}')
          git tag $NEW_VERSION
          git push origin $NEW_VERSION

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Auto-generated Protobuf and version bump to $NEW_VERSION"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
